-- FIXTURE REELLE : la chaine d'import produite par le CLIENT pour un vrai
-- personnage, decodee noeud par noeud.
--
-- Elle sert a un aller-retour exact : notre serialiseur, nourri de ces noeuds, doit
-- reproduire la chaine au caractere pres. C'est la seule verification du format
-- possible sans lancer le jeu — et elle vaut mieux qu'une fixture inventee, puisque
-- c'est Blizzard qui a produit la reference.
GEARPROOF_IMPORT_SAMPLE = {
    text = "CoPAkXBWxkyfx9CbGaHonEAhLxMzyMzwMmZmhZbmZmmZxMzMzMAAAAAmhZmZmZMzYAAzMzMzAAAYgBmxiGLbgsNgNAzYAAAmZAMA",
    version = 2, specID = 250,
    hash = { 228, 21, 88, 49, 41, 127, 113, 47, 108, 134, 118, 160, 39, 1, 132, 75 },
    nodes = {
        { id = 1, maxRanks = 1, rank = 0 },
        { id = 2, maxRanks = 1, rank = 0 },
        { id = 3, maxRanks = 1, rank = 1 },
        { id = 4, maxRanks = 1, rank = 1 },
        { id = 5, maxRanks = 1, rank = 1 },
        { id = 6, maxRanks = 1, rank = 1, choice = 1 },
        { id = 7, maxRanks = 1, rank = 1 },
        { id = 8, maxRanks = 1, rank = 1 },
        { id = 9, maxRanks = 1, rank = 1 },
        { id = 10, maxRanks = 1, rank = 1 },
        { id = 11, maxRanks = 1, rank = 0 },
        { id = 12, maxRanks = 1, rank = 0 },
        { id = 13, maxRanks = 1, rank = 1 },
        { id = 14, maxRanks = 1, rank = 1 },
        { id = 15, maxRanks = 1, rank = 0 },
        { id = 16, maxRanks = 1, rank = 1 },
        { id = 17, maxRanks = 1, rank = 1 },
        { id = 18, maxRanks = 1, rank = 1 },
        { id = 19, maxRanks = 1, rank = 1 },
        { id = 20, maxRanks = 1, rank = 1 },
        { id = 21, maxRanks = 1, rank = 0 },
        { id = 22, maxRanks = 1, rank = 0 },
        { id = 23, maxRanks = 1, rank = 1 },
        { id = 24, maxRanks = 1, rank = 1, choice = 2 },
        { id = 25, maxRanks = 1, rank = 1 },
        { id = 26, maxRanks = 1, rank = 1 },
        { id = 27, maxRanks = 1, rank = 1 },
        { id = 28, maxRanks = 1, rank = 1 },
        { id = 29, maxRanks = 1, rank = 1 },
        { id = 30, maxRanks = 1, rank = 1, granted = true },
        { id = 31, maxRanks = 1, rank = 1 },
        { id = 32, maxRanks = 1, rank = 1 },
        { id = 33, maxRanks = 1, rank = 1, choice = 1 },
        { id = 34, maxRanks = 1, rank = 0 },
        { id = 35, maxRanks = 1, rank = 1 },
        { id = 36, maxRanks = 1, rank = 1 },
        { id = 37, maxRanks = 1, rank = 1 },
        { id = 38, maxRanks = 1, rank = 1 },
        { id = 39, maxRanks = 1, rank = 1 },
        { id = 40, maxRanks = 1, rank = 1 },
        { id = 41, maxRanks = 1, rank = 1 },
        { id = 42, maxRanks = 1, rank = 1 },
        { id = 43, maxRanks = 1, rank = 0 },
        { id = 44, maxRanks = 1, rank = 0 },
        { id = 45, maxRanks = 1, rank = 0 },
        { id = 46, maxRanks = 1, rank = 0 },
        { id = 47, maxRanks = 1, rank = 0 },
        { id = 48, maxRanks = 1, rank = 0 },
        { id = 49, maxRanks = 1, rank = 0 },
        { id = 50, maxRanks = 1, rank = 0 },
        { id = 51, maxRanks = 1, rank = 0 },
        { id = 52, maxRanks = 1, rank = 0 },
        { id = 53, maxRanks = 1, rank = 0 },
        { id = 54, maxRanks = 1, rank = 0 },
        { id = 55, maxRanks = 1, rank = 0 },
        { id = 56, maxRanks = 1, rank = 0 },
        { id = 57, maxRanks = 1, rank = 0 },
        { id = 58, maxRanks = 1, rank = 0 },
        { id = 59, maxRanks = 1, rank = 0 },
        { id = 60, maxRanks = 1, rank = 0 },
        { id = 61, maxRanks = 1, rank = 0 },
        { id = 62, maxRanks = 1, rank = 0 },
        { id = 63, maxRanks = 1, rank = 0 },
        { id = 64, maxRanks = 1, rank = 0 },
        { id = 65, maxRanks = 1, rank = 0 },
        { id = 66, maxRanks = 1, rank = 0 },
        { id = 67, maxRanks = 1, rank = 0 },
        { id = 68, maxRanks = 1, rank = 0 },
        { id = 69, maxRanks = 1, rank = 0 },
        { id = 70, maxRanks = 1, rank = 0 },
        { id = 71, maxRanks = 1, rank = 0 },
        { id = 72, maxRanks = 1, rank = 0 },
        { id = 73, maxRanks = 1, rank = 0 },
        { id = 74, maxRanks = 1, rank = 1 },
        { id = 75, maxRanks = 1, rank = 1 },
        { id = 76, maxRanks = 1, rank = 0 },
        { id = 77, maxRanks = 1, rank = 0 },
        { id = 78, maxRanks = 1, rank = 1 },
        { id = 79, maxRanks = 1, rank = 1 },
        { id = 80, maxRanks = 1, rank = 1 },
        { id = 81, maxRanks = 1, rank = 1 },
        { id = 82, maxRanks = 1, rank = 1 },
        { id = 83, maxRanks = 1, rank = 1 },
        { id = 84, maxRanks = 1, rank = 1 },
        { id = 85, maxRanks = 1, rank = 1 },
        { id = 86, maxRanks = 1, rank = 0 },
        { id = 87, maxRanks = 1, rank = 1 },
        { id = 88, maxRanks = 1, rank = 1 },
        { id = 89, maxRanks = 1, rank = 1 },
        { id = 90, maxRanks = 1, rank = 0 },
        { id = 91, maxRanks = 1, rank = 1 },
        { id = 92, maxRanks = 1, rank = 0 },
        { id = 93, maxRanks = 1, rank = 0 },
        { id = 94, maxRanks = 1, rank = 0 },
        { id = 95, maxRanks = 1, rank = 0 },
        { id = 96, maxRanks = 1, rank = 0 },
        { id = 97, maxRanks = 1, rank = 0 },
        { id = 98, maxRanks = 1, rank = 0 },
        { id = 99, maxRanks = 1, rank = 0 },
        { id = 100, maxRanks = 1, rank = 0 },
        { id = 101, maxRanks = 1, rank = 0 },
        { id = 102, maxRanks = 1, rank = 0 },
        { id = 103, maxRanks = 1, rank = 1 },
        { id = 104, maxRanks = 1, rank = 1 },
        { id = 105, maxRanks = 1, rank = 1 },
        { id = 106, maxRanks = 1, rank = 1 },
        { id = 107, maxRanks = 1, rank = 1 },
        { id = 108, maxRanks = 1, rank = 1 },
        { id = 109, maxRanks = 1, rank = 1 },
        { id = 110, maxRanks = 1, rank = 1 },
        { id = 111, maxRanks = 1, rank = 0 },
        { id = 112, maxRanks = 1, rank = 0 },
        { id = 113, maxRanks = 1, rank = 0 },
        { id = 114, maxRanks = 1, rank = 0 },
        { id = 115, maxRanks = 1, rank = 0 },
        { id = 116, maxRanks = 1, rank = 0 },
        { id = 117, maxRanks = 1, rank = 0 },
        { id = 118, maxRanks = 1, rank = 0 },
        { id = 119, maxRanks = 1, rank = 0 },
        { id = 120, maxRanks = 1, rank = 0 },
        { id = 121, maxRanks = 1, rank = 0 },
        { id = 122, maxRanks = 1, rank = 0 },
        { id = 123, maxRanks = 1, rank = 0 },
        { id = 124, maxRanks = 1, rank = 0 },
        { id = 125, maxRanks = 1, rank = 0 },
        { id = 126, maxRanks = 1, rank = 0 },
        { id = 127, maxRanks = 1, rank = 0 },
        { id = 128, maxRanks = 1, rank = 0 },
        { id = 129, maxRanks = 1, rank = 0 },
        { id = 130, maxRanks = 1, rank = 1 },
        { id = 131, maxRanks = 1, rank = 0 },
        { id = 132, maxRanks = 1, rank = 0 },
        { id = 133, maxRanks = 1, rank = 0 },
        { id = 134, maxRanks = 1, rank = 0 },
        { id = 135, maxRanks = 1, rank = 1 },
        { id = 136, maxRanks = 1, rank = 0 },
        { id = 137, maxRanks = 1, rank = 0 },
        { id = 138, maxRanks = 1, rank = 0 },
        { id = 139, maxRanks = 1, rank = 0 },
        { id = 140, maxRanks = 1, rank = 1 },
        { id = 141, maxRanks = 1, rank = 1 },
        { id = 142, maxRanks = 1, rank = 0 },
        { id = 143, maxRanks = 1, rank = 1, choice = 1 },
        { id = 144, maxRanks = 1, rank = 0 },
        { id = 145, maxRanks = 1, rank = 1, granted = true },
        { id = 146, maxRanks = 1, rank = 1 },
        { id = 147, maxRanks = 1, rank = 0 },
        { id = 148, maxRanks = 1, rank = 1, choice = 1 },
        { id = 149, maxRanks = 1, rank = 1, choice = 2 },
        { id = 150, maxRanks = 1, rank = 0 },
        { id = 151, maxRanks = 1, rank = 0 },
        { id = 152, maxRanks = 1, rank = 0 },
        { id = 153, maxRanks = 1, rank = 0 },
        { id = 154, maxRanks = 1, rank = 0 },
        { id = 155, maxRanks = 1, rank = 1, granted = true },
        { id = 156, maxRanks = 1, rank = 0 },
        { id = 157, maxRanks = 1, rank = 1, choice = 2 },
        { id = 158, maxRanks = 1, rank = 1 },
        { id = 159, maxRanks = 1, rank = 0 },
        { id = 160, maxRanks = 1, rank = 0 },
        { id = 161, maxRanks = 1, rank = 0 },
        { id = 162, maxRanks = 1, rank = 0 },
        { id = 163, maxRanks = 1, rank = 0 },
        { id = 164, maxRanks = 1, rank = 1, choice = 2 },
        { id = 165, maxRanks = 1, rank = 0 },
        { id = 166, maxRanks = 1, rank = 0 },
        { id = 167, maxRanks = 1, rank = 0 },
        { id = 168, maxRanks = 1, rank = 0 },
        { id = 169, maxRanks = 1, rank = 0 },
        { id = 170, maxRanks = 1, rank = 0 },
        { id = 171, maxRanks = 1, rank = 0 },
        { id = 172, maxRanks = 1, rank = 1 },
        { id = 173, maxRanks = 1, rank = 1 },
        { id = 174, maxRanks = 1, rank = 0 },
        { id = 175, maxRanks = 1, rank = 1 },
        { id = 176, maxRanks = 1, rank = 0 },
        { id = 177, maxRanks = 1, rank = 0 },
        { id = 178, maxRanks = 1, rank = 0 },
        { id = 179, maxRanks = 1, rank = 0 },
        { id = 180, maxRanks = 1, rank = 0 },
        { id = 181, maxRanks = 1, rank = 0 },
        { id = 182, maxRanks = 1, rank = 0 },
        { id = 183, maxRanks = 1, rank = 0 },
        { id = 184, maxRanks = 1, rank = 0 },
        { id = 185, maxRanks = 1, rank = 0 },
        { id = 186, maxRanks = 1, rank = 0 },
        { id = 187, maxRanks = 1, rank = 0 },
        { id = 188, maxRanks = 1, rank = 0 },
        { id = 189, maxRanks = 1, rank = 0 },
        { id = 190, maxRanks = 1, rank = 0 },
        { id = 191, maxRanks = 1, rank = 0 },
        { id = 192, maxRanks = 1, rank = 0 },
        { id = 193, maxRanks = 1, rank = 0 },
        { id = 194, maxRanks = 1, rank = 1 },
        { id = 195, maxRanks = 1, rank = 1 },
        { id = 196, maxRanks = 1, rank = 1 },
        { id = 197, maxRanks = 1, rank = 0 },
        { id = 198, maxRanks = 1, rank = 0 },
        { id = 199, maxRanks = 1, rank = 0 },
        { id = 200, maxRanks = 1, rank = 0 },
        { id = 201, maxRanks = 1, rank = 0 },
        { id = 202, maxRanks = 1, rank = 0 },
        { id = 203, maxRanks = 1, rank = 0 },
        { id = 204, maxRanks = 1, rank = 1 },
        { id = 205, maxRanks = 1, rank = 0 },
        { id = 206, maxRanks = 1, rank = 0 },
        { id = 207, maxRanks = 1, rank = 0 },
        { id = 208, maxRanks = 1, rank = 0 },
        { id = 209, maxRanks = 1, rank = 0 },
        { id = 210, maxRanks = 1, rank = 0 },
    },
}
